### ISSUE TITLE
import vs. require

### ISSUE THREAD

**Issue by tonyxiao** [segmentio/specs#26]
I see we use `require` in a whole bunch of places and `import` in other places. Is there any reason we do things differently?

**Comment by stephenmathieson** [comment]
ah, yeah, it's the super weird state of javascript atm. in the browser, we've run everything though babel with [these settings](https://github.com/segmentio/specs/blob/master/.babelrc). this is mainly to handle jsx transformations, but it also gives us the `import/export` syntax. on the server, we're just use vanilla node (not precompiling), so we're using `require` and `module.exports`

**Comment by tonyxiao** [comment]
I see. Is there a reason to not use babel / webpack on the server?

**Comment by stephenmathieson** [comment]
i don't use babel on the server for a few reasons:

1. (the big one) stack traces
2. pre-compiling is a extra (unnecessary) step, since node has native commonjs-ish behavior
3. no jsx

going to close this, since i don't think this is the right forum for discussing commonjs/es6 semantics. feel free to ping me if you have any more questions regarding the topic tho!
